CREATE DATABASE customer_behaviour;

SELECT USER();

SHOW DATABASES;

SELECT *
FROM customer
LIMIT 20;

# What is the total revenue generated by the male and female customers?

SELECT gender,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

# Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied= 'yes' AND
purchase_amount >=
(
SELECT AVG(purchase_amount)
FROM customer
);


# Which are the top 5 products with the highest average review rating?

SELECT item_purchased,ROUND(AVG(review_rating),2) avg_rev
FROM customer
GROUP BY item_purchased
ORDER BY avg_rev DESC
LIMIT 5;


# Compare the average purchase amounts between Standard and Express Shipping.

SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS purch_amo
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


# Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id) AS total_customer, AVG(purchase_amount) avg_purchasing_amount,SUM(purchase_amount) tot_purchasing_amount
FROM customer
GROUP BY subscription_status
ORDER BY avg_purchasing_amount,tot_purchasing_amount;

# Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100*(SUM(CASE
WHEN discount_applied='Yes' THEN 1
ELSE 0
END)/COUNT(*)),2) AS percentage_purchase
FROM customer
GROUP BY item_purchased
ORDER BY percentage_purchase DESC
LIMIT 5;

# Segment customers into New, Returning, and Loyal based on their total number of previous purchases. Show the count of customers in each segment.
WITH cust_seg AS
(
SELECT *,
CASE WHEN previous_purchases<=1 THEN 'New'
WHEN previous_purchases<=10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT customer_segment, count(*) AS number_customer
FROM cust_seg
GROUP BY customer_segment;


# What are the top 3 most purchased products within each category?

WITH num_products AS
(
SELECT category,item_purchased,COUNT(*) AS purchase_count
FROM customer
GROUP BY category,item_purchased
),
top_3_products AS
(
SELECT category,item_purchased,purchase_count,ROW_NUMBER() OVER(PARTITION BY category ORDER BY purchase_count DESC) AS top_3
FROM num_products
)
SELECT *
FROM top_3_products
WHERE top_3<=3;


# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,count(*) num_customers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;


# What is the revenue contribution of each age group?

SELECT age_group, ROUND(100*SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer),2) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC





